import React, { useState } from 'react';

interface ResultInfographicProps {
    // SVG code string OR base64 image data
    content: string;
    // Type: 'svg' or 'image'
    type: 'svg' | 'image';
    onClose: () => void;
}

const ResultInfographic: React.FC<ResultInfographicProps> = ({ content, type, onClose }) => {
    const [isDownloading, setIsDownloading] = useState(false);

    const handleDownload = () => {
        setIsDownloading(true);
        try {
            if (type === 'svg') {
                // SVG download
                const blob = new Blob([content], { type: 'image/svg+xml' });
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = `ai-strategy-card-${new Date().getTime()}.svg`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
            } else {
                // Image download (base64)
                const link = document.createElement('a');
                link.href = content.startsWith('data:') ? content : `data:image/png;base64,${content}`;
                link.download = `ai-strategy-card-${new Date().getTime()}.png`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            }
        } catch (error) {
            console.error('Download failed:', error);
        } finally {
            setIsDownloading(false);
        }
    };

    return (
        <div className="flex flex-col h-full bg-white animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Header */}
            <div className="p-4 border-b flex justify-between items-center">
                <h2 className="font-display font-bold text-xl">Your Strategy Card</h2>
                <button
                    onClick={onClose}
                    className="w-10 h-10 rounded-full flex items-center justify-center hover:bg-gray-100 transition-all"
                >
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#1E3D2F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <line x1="18" y1="6" x2="6" y2="18"></line>
                        <line x1="6" y1="6" x2="18" y2="18"></line>
                    </svg>
                </button>
            </div>

            {/* Content area */}
            <div className="flex-1 overflow-y-auto p-4 md:p-8 flex flex-col items-center gap-6">
                {type === 'svg' ? (
                    <div
                        className="w-full max-w-[500px] aspect-[16/9] rounded-xl shadow-2xl overflow-hidden border-2 border-[#1E3D2F] bg-[#F9F8F6] transition-transform hover:scale-[1.02]"
                        dangerouslySetInnerHTML={{ __html: content }}
                    />
                ) : (
                    <img
                        src={content.startsWith('data:') ? content : `data:image/png;base64,${content}`}
                        alt="AI Strategy Card"
                        className="w-full max-w-[500px] rounded-xl shadow-2xl border-2 border-[#1E3D2F] transition-transform hover:scale-[1.02]"
                    />
                )}

                <div className="text-center max-w-sm">
                    <p className="text-[#1E3D2F] font-body text-sm mb-6">
                        This card was generated based on our conversation. It summarizes your current strategic position and tactical next steps.
                    </p>

                    <button
                        onClick={handleDownload}
                        disabled={isDownloading}
                        className="w-full bg-[#FF6B4A] text-white font-bold py-3 px-6 rounded-full shadow-lg hover:shadow-xl transition-all active:scale-95 disabled:opacity-50"
                    >
                        {isDownloading ? 'Preparing Download...' : `Download Card (.${type === 'svg' ? 'svg' : 'png'})`}
                    </button>
                </div>
            </div>

            {/* Footer / Disclaimer */}
            <div className="p-4 text-center text-[10px] text-gray-400 border-t">
                Generated by aiornot.biz // Experimental AI Strategy Diagnostic
            </div>
        </div>
    );
};

export default ResultInfographic;
